version: "{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
build_script:
- ps: .\build.ps1 -target "BuildAndPack"
test: off #tests handled by cake script
deploy: off
artifacts:
  - path: 'artifacts/*.nupkg'
  - path: 'artifacts/*.report.xml'
